name: ZombieApocalypse
version: '${project.version}'
main: com.github.lybinhminh.zombieapocalypse.Main
api-version: 1.16
authors: [ unfish ]
commands:
  maps:
    permission: za.infoshow
  debug:
    permission: za.plugin
  infect:
    permission: za.game

